a = 1


def myFun():
    b = 2
    print("a = ", a)
    print("b = ", b)


myFun()
print(a)
# print(b) ERROR!
